config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post 'items/new' => 'items#new', as: :new_item

  get 'items' => 'items#index'

  patch '/items/:id/' => 'items#update'

get 'clothing/index' => 'clothing#index',       as: :clothing
get 'electronics/index' => 'electronics#index', as: :electronics
get 'furniture/index' => 'furniture#index',     as: :furniture
get 'housing/index' => 'housing#index',         as: :housing
get 'misc/index' => 'misc#index',               as: :misc
get 'school/index' => 'school#index',           as: :school
get 'services/index' => 'services#index',       as: :services

  resources :items do
    resources :comments
  end
  get 'index', to: 'index/index'
  root to: 'clothing#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  validates :contents, presence: true, allow_blank: false
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :photos, dependent: :destroy
	belongs_to :user
	validates :title, :summary, :price, :location, :category, presence: true
	default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
	gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :name, :email, :password
  has_many :comments
  has_many :items
end

app/controllers/clothing_controller.rb
class ClothingController < ApplicationController
  def index
    @items = Item.where(category: "clothing")
    render 'items/index'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@item = Item.find(params[:item_id])
		@comment = @item.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to redirect_handler(@item)
	end

	def destroy
		@item = Item.find(params[:item_id])
		@comment = @item.comments.find(params[:id])
		@comment.destroy
		redirect_to redirect_handler(@item)
	end

	private
		def comment_params
			params.require(:comment).permit(:contents, :item)
		end
end

app/controllers/furniture_controller.rb
class FurnitureController < ApplicationController
  def index
    @items = Item.where(category: "furniture")
    render 'items/index'
  end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController
  def index
    @items = Item.where(category: "housing")
    render 'items/index'
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
  	@item = Item.new
  end


  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.save

    redirect_to redirect_handler(@item)

  end

  def edit
  	@item = Item.find(params[:id])
  end


  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		redirect_to @item
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@item = Item.find(params[:id])
  	@item.destroy
  	redirect_to items_path
  end

  private
  	def item_params
  		params.require(:item).permit(:title, :summary, :location, :price, :category)
  	end

end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
  def index
    @items = Item.where(category: "miscellaneous")
    render 'items/index'
  end
end

app/controllers/school_controller.rb
class SchoolController < ApplicationController
  def index
    @items = Item.where(category: "school")
    render 'items/index'
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @items = Item.where(category: "services")
    render 'items/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothing_helper.rb
module ClothingHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/furniture_helper.rb
module FurnitureHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/clothing/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Clothing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/application.css">
  <%= stylesheet_link_tag "application.css" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


</head>
<body>


<nav class="navbar navbar-default">
  <div class="container">
    <div>
      <ul class="nav navbar-nav">
        <li><a href="/clothing/index">Clothing</a></li>
        <li><a href="../../furniture/index">Furniture</a></li>
        <li><a href="../../electronics/index">Electronics</a></li>
        <li><a href="../../housing/index">Housing</a></li>
        <li><a href="../../school/index">School</a></li>
        <li><a href="../../services/index">Services</a></li>
        <li><a href="../../misc/index">Misc</a></li>
      </ul>
    </div>
  </div>
</nav>

<!--
  add item buttom
  add item page
  login page
  logout button
  @user name + credits or login

  -->
<div class="container">
  <% @items.each do |item| %>
    <% if item.category == "clothing" %>
      <div class="panel panel-default item-entry">

          <div class="panel-heading">
            <h2 class="item-title">
              <%= item.title %>
              <small>Posted by <%= item.user.name || item.user_id %> on <%= item.created_at.to_time.strftime('%b %-d, %Y') %></small>
            </h2>
          </div>

          <div class="panel-body item-body">
            <!-- <div class="item-entry_photo col-xs-4">
              <%= item.photos %>
            </div> -->
            <div class="row">
              <div class="col-xs-4 item-details">
                <h4>Item Summary</h4>
                <p><%= item.summary %></p>
                <h4>Pickup Location</h4>
                <p><%= item.location %></p>
              </div>

              <div class="col-xs-8">
                <h4>Item Discussion</h4>

                <% @comments.each do |comment| %>
                  <% if comment.item == item %>
                    <div class="media comment">
                      <div class="media-left">
                        <a href="#">
                          <img src="http://systemout.net/images/Gravatar-icon.png" alt="" class="media-object comment-icon">
                        </a>
                        <small class="user-info text-center"><%= comment.user.name || comment.user_id %></small>
                      </div>
                      <div class="media-body">
                        <p class="comment">
                          <%= comment.contents %>
                        </p>
                        <p class="small user-info pull-right">
                          <em>Posted at <%= comment.created_at.to_time.strftime('%-I:%M%P on %b %-d, %Y') %></em>
                        </p>
                      </div>
                      <hr>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    <% end %>
  <% end%>

</div>
</body>
</html>

app/views/items/index.html.erb
<!--
  add item buttom
  add item page
  login page
  logout button
  @user name + credits or login

  -->
<div class="container">
  <% @items.each do |item| %>
      <div class="panel panel-default item-entry">

          <div class="panel-heading">
            <h2 class="item-title">
              <%= item.title %>
              <small>Posted by <%= item.user.name || item.user_id %> on <%= item.created_at.to_time.strftime('%b %-d, %Y') %></small>
            </h2>
          </div>

          <div class="panel-body item-body">
            <div class="row">
              <div class="col-xs-4 item-details">
                <h4>Item Price</h4>
                <p>$<%= number_with_precision(item.price, :precision => 2, :delimiter => ',') %></p>
                <h4>Item Summary</h4>
                <p><%= item.summary %></p>
                <h4>Pickup Location</h4>
                <p><%= item.location %></p>
              </div>

              <div class="col-xs-8">
                <h4>Item Discussion</h4>

                <% item.comments.each do |comment| %>
                    <div class="media comment">
                      <div class="media-left">
                        <a href="#">
                          <img src="http://systemout.net/images/Gravatar-icon.png" alt="" class="media-object comment-icon">
                        </a>
                        <small class="user-info text-center"><%= comment.user.name %></small>
                      </div>
                      <div class="media-body">
                        <p class="comment">
                          <%= comment.contents %>
                        </p>
                        <p class="small user-info pull-right">
                          <em>Posted at <%= comment.created_at.to_time.strftime('%-I:%M%P on %b %-d, %Y') %></em>
                        </p>
                      </div>
                      <hr>
                    </div>
                <% end %>

                <h4>Post New Comment</h4>
                <%= simple_form_for item.comments.new, url: item_comments_path(item) do |f| %>
                  <%= f.input :contents, as: :text %>
                  <%= f.button :submit %>
                <% end %>

              </div>
            </div>
          </div>
      </div>
  <% end %>

  <%= button_to "Submit New Item", new_item_path, {:class => "new-item-btn btn btn-primary"} %>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>Submit a New Item <small>Sell your old stuff</small></h1>
  <hr>
  <%= simple_form_for @item do |f| %>
    <%= f.input :title %>
    <%= f.input :summary, as: :text %>
    <%= f.input :price %>
    <%= f.input :location %>
    <%= f.input :category, :collection => ['clothing', 'furniture', 'electronics', 'housing', 'school', 'services', 'misc'] %>
    <%= f.button :submit %>
  <% end %>
</div>