config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post 'items/new' => 'items#new', as: :new_item

  get 'items' => 'items#index'

  patch '/items/:id/' => 'items#update'

get 'clothing/index' => 'clothing#index',       as: :clothing
get 'electronics/index' => 'electronics#index', as: :electronics
get 'furniture/index' => 'furniture#index',     as: :furniture
get 'housing/index' => 'housing#index',         as: :housing
get 'misc/index' => 'misc#index',               as: :misc
get 'school/index' => 'school#index',           as: :school
get 'services/index' => 'services#index',       as: :services

  resources :items do
    resources :comments
  end
  get 'index', to: 'index/index'
  root to: 'clothing#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  validates :contents, presence: true, allow_blank: false
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :photos, dependent: :destroy
	belongs_to :user
	validates :title, :summary, :price, :location, :category, presence: true
	default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
	gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :name, :email, :password
  has_many :comments
  has_many :items
end

app/controllers/clothing_controller.rb
class ClothingController < ApplicationController
  def index
    @items = Item.where(category: "clothing")
    render 'items/index'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@item = Item.find(params[:item_id])
		@comment = @item.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to redirect_handler(@item)
	end

	def destroy
		@item = Item.find(params[:item_id])
		@comment = @item.comments.find(params[:id])
		@comment.destroy
		redirect_to redirect_handler(@item)
	end

	private
		def comment_params
			params.require(:comment).permit(:contents, :item)
		end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController
  def index
    @items = Item.where(category: "housing")
    render 'items/index'
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
  	@item = Item.new
  end


  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.save

    redirect_to redirect_handler(@item)

  end

  def edit
  	@item = Item.find(params[:id])
  end


  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		redirect_to @item
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@item = Item.find(params[:id])
  	@item.destroy
  	redirect_to items_path
  end

  private
  	def item_params
  		params.require(:item).permit(:title, :summary, :location, :price, :category)
  	end

end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
  def index
    @items = Item.where(category: "miscellaneous")
    render 'items/index'
  end
end

app/controllers/school_controller.rb
class SchoolController < ApplicationController
  def index
    @items = Item.where(category: "school")
    render 'items/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothing_helper.rb
module ClothingHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/furniture_helper.rb
module FurnitureHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Free &amp; For Sale</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%= image_tag current_user.gravatar_url %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<nav class="navbar navbar-default">
  <div class="container">
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Clothing",    clothing_path %>   </li>
        <li><%= link_to "Furniture",   furniture_path %>  </li>
        <li><%= link_to "Electronics", electronics_path %></li>
        <li><%= link_to "Housing",     housing_path %>    </li>
        <li><%= link_to "School",      school_path %>     </li>
        <li><%= link_to "Services",    services_path %>   </li>
        <li><%= link_to "Misc",        misc_path %>       </li>
      </ul>
    </div>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/Users/stevenelleman/Desktop/rails_decal/proj2/free_for_sale_css.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<div class="banner"> </div>

<div class="enter"> 
  <div class="login">
  </div>

  <div class="sign_up">

  </div>
</div>
</body>
</html>

app/views/login/show.html.erb
<div class="banner"> </div>

<div class="enter">
  <div class="login">
  </div>

  <div class="sign_up">

  </div>
</div>